env:
  browser: true
  es2021: true
  jquery: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  linebreak-style: ["warn", "unix"]
  indent: ["warn", 2]
  strict: ["warn", "global"]
  no-alert: ["warn"]
